# -*- coding: utf-8 -*-
"""Exercício-módulo-1-calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LbGod8adeb98fhYLc4TkIlpSgXsh410t
"""



"""##Calculadora - Exercício 1

"""

num1 = int(input("Primeiro número:"))
num2 = int(input("Segundo número"))
operacao = input("Operação: +, -, *, /")
if operacao == "+":
  print(num1 + num2)
elif operacao == "-":
  print(num1 - num2)
elif operacao == "*":
  print(num1 * num2)
elif operacao == "/":
  print(num1 / num2)
else:
  print("Operação inválida")